= Agnostic-Content generation

== Definition
This component will allow generate a static website with your ASCII docs(adoc) files.
It consist in 1 playbook which will use Antora to generate static html based on your doc repository.


== Project structure:

* build

* playbooks
Ansible playbook will generate your website using Antora.

* modules
** ROOT

* build
All the html files generated by the playbook, images and UI.  

* antora.yml is the antora component definition. It contains project definition, version, root page and file navigation path.
More information: https://docs.antora.org/antora/2.2/component-descriptor/
* nav.adoc is the navigation definition file for your website content(adoc). 
 The format is based on :
 Ex. * xref:index.adoc[Lab Overview]
 For more information about navigation structure:
https://docs.antora.org/antora/2.2/navigation/list-structures/

== Steps to setup your environment

*Pre-reqs:*

* Ansible: 2.9.10 installed
Installing Ansible with PIP
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python get-pip.py --user

More information: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#from-pip


* Antora version: 2.2 installed
Installing Antora using Node
 npm i -g @antora/cli@2.2 @antora/site-generator-default@2.2


For more information:
How to install Node:
https://docs.antora.org/antora/2.2/install/macos-requirements/
How to install Antora:
https://docs.antora.org/antora/2.2/install/install-antora/

*Installation:*

. Download the source code from the repository
git clone https://github.com/redhat-gpte-devopsautomation/agnosticlp-content.git

. Goto your downloaded source folder: agnosticlp-content

. Goto

. Run antora playbooks/antora-playbook.yml
After the first time, if you done changes in your repo use: antora --fetch playbooks/antora-playbook.yml