- hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - input.yml
  vars:
    adoc_dir: "../templates"
  tasks:    
  - name: Process jinja templates
    loop: >-
      {{ lookup('filetree', adoc_dir) | to_json | from_json
       | json_query("[?state=='file' && ends_with(src, '.j2')].src")
      }}
    vars:
      dest: >-
        {{ item | regex_replace('\.j2$', '') }}
    template:
      src: "{{ item }}"
      dest: "{{ dest }}"
