env:
  - name : Docker
    guid: sbor
    ocp_username: "sborenst-redhat.com" 
    user_info_messages: "A bookbag image has been created in project bookbag.\nThe bookbag imagestream is rhtr2020pipelines:latest."