= Welcome to Component B!

This is the automatic start page for version *{page-component-version}* of Component B.

Component B is one of two documentation components in the Antora Demo.
The other docs component, Component A, can be accessed via the component selector menu (aka component drawer) at the bottom of the menu on the left side of the page.

== Page source

This page is sourced from the AsciiDoc file named [.path]_index.adoc_ that is located at [.path]/modules/ROOT/pages_.


=== Why is this the home page of the Antora Demo site?

This page is used as the home page for the Antora Demo because it is assigned as the site `start_page` in the Demo site's playbook file [.path]_site.yml_.

== Cross reference syntax to target this page

To create a cross reference *to this page from another page in the ROOT module of Component B*, the xref syntax would be `\xref:index.adoc[]`.

To create a cross reference *to this page from a page in Module One of Component B*, the xref syntax would be `\xref:ROOT:index.adoc[]`.

