- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    adoc_dir: "../templates"
  tasks:
  - name: Include Vars
    include_vars:
      file: input/input.yaml
  - name: show templating results
    debug:
      msg: "{{ lookup('template', '../templates/add_webhook.adoc.je') }}"     
  - name: Process jinja templates
    loop: >-
      {{ lookup('filetree', adoc_dir) | to_json | from_json
       | json_query("[?state=='file' && ends_with(src, '.j2')].src")
      }}
    vars:
      dest: >-
        {{ item | regex_replace('\.j2$', '\.adoc') }}
    template:
      src: ../templates
      dest: ../modules
